language: node_js
sudo: false
dist: trusty
node_js:
  - '10.14.2'

addons:
  packages:
    - unzip
    - google-chrome-stable

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - sudo apt-get clean
  - sudo apt-get update
  - sudo apt-get install dpkg
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - yarn install

after_failure:
  - cat /home/travis/build/puniwrex/ngx-print/yarn-error.log

after_success:
  - cat ./dist/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email: false

script:
  - yarn run test && yarn run build
